name: "Checks and dev env deploy"

on:
  push:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine yapf sphinx sphinx_rtd_theme
          pip install shapely
          pip install -r requirements.txt
          pip install -r requirements_prod.txt
      - name: Check formatting
        run: yapf -p -r --diff superannotate
      - name: Check docs
        run: make docs
  deploy_dev:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
  
